name: PowerShell script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Powershell:
    runs-on: self-hosted

    steps:
    
    - name: Run Get-Service
      shell: powershell
      run: |
        Write-Host "Below are the running Services on Runner"
        Get-Service | Where-Object {$_.Status -eq "Running"}

